### ISSUE TITLE
Not a valid plugin artifact

### ISSUE THREAD

**Issue by RichJson** [cloudflare/cloudflare-access-for-atlassian#39] opened 2019-05-21 16:20 UTC
Tried installing the plugin using the Manage apps page, using the 2.8.0 .jar url from Github.

I'm getting the following error:
>java.lang.IllegalArgumentException: The artifact URI file:/var/atlassian/application-data/confluence/plugins-cache/1558455296169plugin.8557078419278506534.810dc300-2b33-11e9-91ce-63131dc7380e is not a valid plugin artifact

I'm using the latest [Confluence Server image](https://hub.docker.com/r/atlassian/confluence-server/).

**Comment by felipebn** [comment] 2019-05-28 15:32
Hi @RichJson,

I was not able to reproduce using the URL below.

https://github.com/cloudflare/cloudflare-access-for-atlassian/releases/download/v2.8.0/cloudflare-access-confluence-plugin-2.8.0.jar 

Maybe the download was incomplete/corrupted.
Could you provide a md5sum of the file indicated in the error message? 

```
md5sum /var/atlassian/application-data/confluence/plugins-cache/1558455296169plugin.8557078419278506534.810dc300-2b33-11e9-91ce-63131dc7380e
```
Expected hash should be: `ef9da320529ace4c3abccd69faf4d9f2`.

**Comment by felipebn** [comment] 2020-04-18 16:45
Closing this due to missing feedback, please reopen if needed.

**Closed by felipebn** 2020-04-18 16:45 UTC
Labels: awaiting reply
